config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	VALID_EMAIL_REGEX = /\A^(?!.*\.{2})[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	before_save { email.downcase! }
	validates :name, presence: true, length: { maximum: 50 }
	validates :email, presence: true,  length: { maximum: 255 }, 
					  format: { with: VALID_EMAIL_REGEX },
					  uniqueness: { case_sensitive: false }
	has_secure_password	
  	validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Project Playground!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                     :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Ruby Project Playground'
    
    if page_title.empty?
        base_title
  	else
  		page_title + ' | ' + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_fonts.html.erb
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lobster" />
<link href="https://fonts.googleapis.com/css?family=Lemonada" rel="stylesheet">

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    SherOn Bala, © 2017
  </small>
  <nav>
    <ul>
      <li>
        <%= link_to "Sign Up", signup_path %>
      </li>
      <li>
        <%= link_to "Login", '#' %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand">
                <%= active_link_to "Judacribz", root_path, active: :exclusive %>
            </div>
        </div>
        <div id="nav-main" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-default navbar-right">
                <li>
                    <%= active_link_to "About", about_path %>
                </li>
                <li>
                    <%= active_link_to "Help", help_path %>
                </li>
                <li>
                    <%= active_link_to "Contact", contact_path %>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all', 
                        'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= full_title(yield(:title)) %></title>   
    <%= render 'layouts/fonts' %>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
</head>

<body>
    <%= render 'layouts/header' %>
    <div id="body_container" class="container centered col-xs-12 col-sm-10">
        <div class="jumbotron">
            <% flash.each do |message_type, message| %>
                <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
            <% end %>
            <%= yield %>
        </div>
        <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<hr>
<p>Where
    <em id="shit"><a href="http://www.urbandictionary.com/define.php?term=shit">
		shit
	</a></em> happens!
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<hr>
<div class="row">
    <div class="col-md-5">
        <form>
            <div class="form-group">
                <div class="col-10">
                    <input class="form-control" type="email" value="EMAIL" required>
                </div>
            </div>
            <div class="form-group">
                <div class="col-10">
                    <input class="form-control" type="text" value="NAME">
                </div>
            </div>
            <div class="form-group">
                <div class="col-10">
                    <input class="form-control" type="text" value="MESSAGE.." required>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <p class="col-md-6 col-md-offset-1">
        Please feel free to leave a message.
    </p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<hr>
<p>Get help on the Ruby on Rails Tutorial at the
	<a href="http://www.railstutorial.org/help">
		Rails Tutorial help section
	</a>. To get help on this sample app, see the
    <a href="http://www.railstutorial.org/book">
    	<em>Ruby on Rails Tutorial</em> book
    </a>.
</p>

app/views/static_pages/home.html.erb
<h1>Project Playground</h1>
<hr>
<p><span id="ruby">Ruby</span> on Rails</p>
<h5 class="text-right">Background
	<span class="glyphicon glyphicon-camera"></span> taken by 
	<a href="https://www.instagram.com/judacribz/">
		<em>Judacribz</em>
	</a>
</h5>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user, url: signup_path) do |f| %>
            <%= render 'shared/error_messages' %>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
    <aside class="col-xs-12">
        <section class="user_info text-center">
            <h1>
    			<%= gravatar_for @user %>
    			<%= @user.name %>
  			</h1>
        </section>
    </aside>
</div>